using BOOSE.BOOSEarchitecture;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BOOSE.Interfaces
{
    /// <summary>
    /// Interface for BOOSE commands. Any Command class should implement this interface and be generated by a CommandFactory that implements the ICommandFactory interface.
    /// Contains methods to set the Command up after its creation, manage its parameters when it is compiled and execute it when it is called.
    /// </summary>
    public interface ICommand
    {
        /// <summary>
        /// Set a Command Object to work with the BOOSE compile and execute system.
        /// </summary>
        /// <param name="Program">Reference to valid StoredProgram</param>
        /// <param name="Params">Original parameter list e.g. "num1,num2"</param>
        void Set(StoredProgram Program, String Params);
        /// <summary>
        /// Called by a BOOSE Parser when after the command has been created by a CommandFactory. parameter list is passed to the object. 
        /// Object should Add() itself to the provided StoredProgram,
        /// </summary>
        /// <returns></returns>

        void Compile();
        /// <summary>
        /// Called by a BOOSE Parser after it has called Set(). Any Command should set up its parameters in this method. i.e. string parameterlist is broken up and parsed. The command then does what it is designed to do.
        /// </summary>
        /// <returns></returns>
        void Execute();

        /// <summary>
        /// Checks that a Command has the right number of parameters and throws a CommandException if not. 
        /// </summary>
        /// <param name="Parameters"></param>
        void CheckParameters(String[] Parameters);

    }
}